modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="blahaj"
version="1.0.0"
displayName="Blahaj!"
description='''
Adds IKEA plushies to Minecraft!
'''
logoFile="icon.png"

[[dependencies.blahaj]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blahaj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
